version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: easycon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:8.0
    container_name: easycon_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: easycon_mosquitto
    ports:
      - "1883:1883"
    user: "${UID}:${GID}"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/certs/:/certs/
